services:
  - type: web
    name: upwork-scraper
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      apt-get update
      apt-get install -y google-chrome-stable
      npm install
    startCommand: CHROME_PATH=/usr/bin/google-chrome npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
